config/routes.rb
Rails.application.routes.draw do

	root :to => "static#home"
	get '/login' => "sessions#new"
	post '/sessions' => "sessions#create"
	get '/logout' => "sessions#destroy"

	resources :sights
	resources :categories
	resources :sight_cats
	
	resources :users do
		resources :sights, only: [:show, :index, :new]
	end

	get "/:page" => "static#show"
	get '/auth/:provider/callback' => 'sessions#omniauth'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :sight_cats
  has_many :sights, through: :sight_cats
end

app/models/sight.rb
class Sight < ApplicationRecord
	belongs_to :user, optional: true
    has_many :sight_cats
    has_many :categories, through: :sight_cats
    accepts_nested_attributes_for :sight_cats

	validates :title, presence: true
	validates :title, length: { minimum: 2 }
  	validates :content, length: { maximum: 500 }

  	scope :search_category, -> (category_name) { 
    joins(sight_cats: :category).where("name LIKE ?", "%#{category_name}%")
  }

    def sight_cats_attributes=(sight_cat_attributes)
    sight_cat_attributes.values.each do |sight_cat_attribute|
      sight_cat = SightCat.find_or_create_by(sight_cat_attribute)
      self.sight_cats << sight_cat
    end
  end
end

app/models/sight_cat.rb
class SightCat < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :sight, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sights, dependent: :destroy
  has_secure_password

  validates :name, presence: true, length: { minimum: 2 }
  validates :email, presence: true, uniqueness: true, length: { minimum: 6 }, format: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  validates :password, presence: true

    def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_initialize do |user|
      user.email = auth.info.email
      user.password = SecureRandom.hex
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :exception

  def authentication_required
    if !logged_in?
      flash[:danger] = "You must be logged in to access the app"
      redirect_to login_path
    end
  end

  def logged_in?
    !!current_user
    #session[:user_id]
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # Explicitly tell ActionView to use a helper method in a view
  helper_method :current_user

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all 
    @searched_category = Category.find_by(name: params[:category_name])
  end

  def show
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(:email => params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Successfully logged in!"
      redirect_to root_path
    else
      flash.now[:danger] = "Invalid email/password combination"
      render 'sessions/new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Sucessfully logged out!"
    redirect_to root_path
  end

  def omniauth
    @user = User.from_omniauth(auth)
    @user.save
    session[:user_id] = @user.id
    redirect_to root_path
  end

  private
  def auth
    request.env['omniauth.auth']
  end


end

app/controllers/sight_cats_controller.rb
class SightCatsController < ApplicationController

  def index
    @sight_cats = SightCat.all 
  end

  def show
  end

end

app/controllers/sights_controller.rb
class SightsController < ApplicationController
	before_action :authentication_required

	def index
      if params[:user_id]
        @sights = User.find(params[:user_id]).sights
      elsif params[:category_name]
      	@sights = Sight.search_category(params[:category_name])
      else
        @sights = Sight.all
      end
    end

	def show
      @sight = Sight.find(params[:id])
	end

  	def new
      @sight = Sight.new
      #@bird.build_category
  	end

	def create
	  @sight = current_user.sights.build(sight_params)
		if @sight.save
			flash[:success] = "Your sighting was sucessfully created!"
		  	redirect_to sight_url(@sight)
	  	else
	  	 	flash[:danger] = "Please try again"
			@sights = Sight.all
			render :index
		end
	end

	def edit
	  @sight = Sight.find(params[:id])
	end

	def update
	  @sight = Sight.find(params[:id])
	  if @sight.update(sight_params)
		  flash[:success] = "Your sighting was sucessfully updated!"
	      redirect_to sight_path(@sight)
	  else
	  	render :edit
	  end
	end

	def destroy
      @sight = Sight.find(params[:id]).destroy
      flash[:success] = "Your sighting was sucessfully deleted!"

      #back to index
	  redirect_to sights_path
  end

	def sight_params #strong parameters
	  params.require(:sight).permit(:title, :content, category_ids:[], categories_attributes: [:name], sight_cats_attributes: [:location])
	end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
	def show
      	render params[:page]
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
      @user = User.new
    end

	def create
	  @user = User.new(user_params)

	  if @user.save
	  	flash[:success] = "Welcome to the App!"
	  	session[:user_id] = @user.id
	  	redirect_to root_path #=> GET "/"

	  else
	  	render 'users/new' #show them the form
	  end
	end

	def show
		@user = User.find(params[:id])
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sights_helper.rb
module SightsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<p>category index</p><BR>


<p>how do I get the sight titles now?</p>

<p style="font-weight: bold">The category you chose:</p>

<%= @searched_category.name %>


<% @searched_category.sights.each do |sight| %>
<%= sight %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.typekit.net/bxx3rsq.css">

    <title>NatureSightings</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation -->
  <nav class="navbar navbar-expand-lg static-top navbar-light" style="background-color: #a3b85e;">
  <div class="container">
    <a class="navbar-brand" href="#" style="font-family: bello-caps, sans-serif; color: white;">Nature Sightings</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#"></a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="/users/<%= current_user.id %>" >User profile</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="/home">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/about">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/sights">Sightings</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/logout">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

    <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    </div>

    <%= yield %>

  </body>
</html>

app/views/sight_cats/index.html.erb
<div class="container"><BR>
<h1>All locations</h1>
<ul style="list-style-type: none; padding: 0; margin: 0;">
      <% @sight_cats.each do |sight_cat| %>
        <li><%= sight_cat.location %></li>
      <% end %>
    </ul><BR>
</div>

app/views/sights/_form.html.erb
<%= form_for(@sight) do |f| %>
  <% if @sight.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@sight.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @sight.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>

  <div class="field">
    <%= f.label :sight_cats, :location %><br />
    <%= f.fields_for :sight_cats, @sight.sight_cats.build do |sight_cats_fields| %>
    <%= sight_cats_fields.text_field :location %>
  <% end %>
  </div>
  

  <div class="field">
    
    <%= hidden_field_tag "sight[category_ids][]", nil %>
    
    <% Category.all.each do |category| %>
      <%= check_box_tag "sight[category_ids][]", 
        category.id, 
        @sight.category_ids.include?(category.id), 
        id: dom_id(category) %>
      <%= label_tag dom_id(category), category.name %><br>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sights/edit.html.erb
<div class="container"><BR>

<h1>Editing "<%= @sight.title %>"</h1>
<%= render 'form' %>
<%= link_to "Back", :back %>

</div>

app/views/sights/index.html.erb
<div class="container"><BR>
<h1>Sightings</h1>
<p>Click author to see all by author</p>

<div id="sights">

  <% @sights.each do |sight| %>
    <div class="sight">
    <%= link_to sight.title, sight_path(sight) %>,
    posted by: <%= link_to sight.user.name, user_sights_path(sight.user) %>,
    category: <%= sight.categories.map { |category| category.name }.join(', ') %>
  <% end %>

</div><BR>

<a href="/sights/new" class="w7-button w7-1">add a sighting</a>
<a href="/sights" class="w7-button w7-1">full list</a><BR><BR>

<b>See sights by category: air, land, water, other</b>

<%= form_tag("/sights", method: "get") do %>
<%= label_tag(:category_name, "Which category?") %>
  <%= text_field_tag(:category_name) %>
  <%= submit_tag("Search") %>
<% end %>

<BR><p>You're logged in as: <%= current_user.name %></p>
</div>

app/views/sights/index.js.erb
$('#sights').append('<%= j render(@sights) %>');
<% if @sights.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@products) %>');
<% else %>
  $('.pagination').remove();
<% end %>
<% sleep 1 %>

app/views/sights/new.html.erb
<div class="container"><BR>
<h1>New sighting: What did you see?</h1>
<%= render 'form' %>
<%= link_to "Back", :back %>
</div>

app/views/sights/show.html.erb
<div class="container">

<!-- Portfolio Item Heading -->
  <h1 class="my-4"><%= @sight.title %></h1>

  <!-- Portfolio Item Row -->
  <div class="row">
    <div class="col-md-8">
    <img class="img-fluid" <%= image_tag("small_bird.jpg", :alt => "bird photo") %><BR>
    </div>

    <div class="col-md-4">
      <h3 class="my-3"><%= @sight.title %> notes</h3>
      <p><%= @sight.content %></p>

<b>Categories:</b>
<ul style="list-style-type: none; padding: 0; margin: 0;">
      <% @sight.categories.each do |category| %>
        <li><%= category.name %></li>
      <% end %>
    </ul><BR>

<b>Author</b>
<p><%= @sight.user.name %></p>

<b>Locations</b>
<ul style="list-style-type: none; padding: 0; margin: 0;">
      <% @sight.sight_cats.each do |sight_cat| %>
        <li><%= sight_cat.location %></li>
      <% end %>
    </ul><BR>

<%= link_to "Back", :back%><BR><BR>

<% if @sight.user == current_user %>
  <a href="/sights/<%= @sight.id %>/edit" class="w7-button">Edit</a>
  <%= button_to "delete", sight_path(:id => @sight), :method => :delete, 
    data: {confirm: "Are you sure you want to delete?"}, 
    :style => 
    "background-color: #A3B85E;
    border: none;
    border-radius: 4px;
    color: white;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-family: sans-serif;
    font-size: 16px;
    margin: 8px 4px;
    padding: 4px 20px;
    cursor: pointer;" %>
<% end %>

</div>

app/views/users/new.html.erb
<div class="container"><BR>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<h1>Sign up here</h1>
<%= form_for(@user) do |f| %>
  <%= f.text_field :name, :placeholder => "Name" %>
  <%= f.text_field :email, :placeholder => "Register with email" %>
  <%= f.password_field :password, :placeholder => "Choose a password" %>
  <%= f.submit %>
<% end %>
</div>

app/views/users/show.html.erb
<div class="container"><BR>
<h1><%= @user.name %></h1>
<p>Sights:</p>
<% @user.sights.each do |sight| %>
  <div><%= sight.title %></div>
<% end %>
</div>